networks:
  monitor:
    driver: bridge

services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - monitor
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus
    ports:
      - 9090:9090
    networks:
      - monitor
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=test
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - monitor
    restart: always

  redis-exporter:
    container_name: redis-exporter
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - 9121:9121
    depends_on:
      - prometheus
    networks:
      - monitor
    restart: always

  loki:
    image: grafana/loki:latest
    container_name: loki
    networks:
      - monitor
    ports:
      - 3100:3100
    volumes:
      - ./loki/config:/etc/loki
      - ./loki/data:/loki
    restart: always

  promtail:
    image: grafana/promtail:2.7.1
    container_name: promtail
    networks:
      - monitor
    volumes:
      - ./promtail/config:/etc/promtail/config.yml
      - /var/log/redis:/var/log/redis
    depends_on:
      - loki
    restart: always    
